#!/usr/bin/env perl

$common_opts = '-halt-on-error -file-line-error';
$latex = 'uplatex ' . $common_opts;
# $pdflatex = 'luajittex --fmt=luajitlatex.fmt ' . $common_opts;
$pdflatex = 'lualatex  ' . $common_opts;
$dvipdf = 'dvipdfmx %O -o %D %S';
# $bibtex = 'pbibtex ';
$bibtex = 'pbibtex %O -kanji=utf8 %B';
$makeindex = 'mendex %O -U %B';

$pdf_mode = 3;
